# Generated by Django 5.0.3 on 2024-03-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="city",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
