# Generated by Django 5.0.3 on 2024-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="accountNumber",
            new_name="econetNumber",
        ),
        migrations.AddField(
            model_name="user",
            name="is_scientist",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_supervisor",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Analysis Manager"),
                    ("supervisor", "Anaysis Supervisor"),
                    ("analysis", "Data Scientist"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
