# Generated by Django 5.0.3 on 2024-04-14 20:25

import django.db.models.deletion
import kpi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0003_user_city_analysisvaribales_commentreports_dataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        null=True,
                        upload_to="",
                        validators=[kpi.models.validate_site_name_extension],
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
