# Generated by Django 5.0.3 on 2024-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0004_user_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technition", "Technition"),
                    ("admin", "Manager"),
                    ("supervisor", "Anaysis Supervisor"),
                    ("technition", "Technition"),
                    ("ceo", "CEO"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
