# Generated by Django 5.0.3 on 2024-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0004_sitename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technition", "Technition"),
                    ("team-leader", "Team Leader"),
                    ("admin", "Analysis Manager"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
