# Generated by Django 5.0.3 on 2024-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0005_alter_user_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_scientist",
            new_name="is_analysis",
        ),
        migrations.AddField(
            model_name="user",
            name="is_technition",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technition", "Technition"),
                    ("admin", "User Manager"),
                    ("supervisor", "Anaysis Supervisor"),
                    ("analysisManager", "anaysisManager"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
