# Generated by Django 5.0.3 on 2024-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0005_alter_user_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("region1", "Region1[Harare,Bulawayo,Gweru]"),
                    ("region2", "Reion2[Chitungwiza,Mutare,Kwekwe,Kadoma]"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="city",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Harare", "Harare"),
                    ("Bulawayo", "Bulawayo"),
                    ("Gweru", "Gweru"),
                    ("Chitungwiza", "Chitungwiza"),
                    ("Mutare", "Mutare"),
                    ("Kwekwe", "Kwekwe"),
                    ("Kadoma", "Kadoma"),
                    ("Masvingo", "Masvingo"),
                    ("Norton", "Norton"),
                    ("Chinhoyi", "Chinhoyi"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
