# Generated by Django 5.0.3 on 2024-05-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0006_remove_user_city_user_region_delete_city_user_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentreports",
            name="fullReportFile",
        ),
        migrations.AlterField(
            model_name="commentreports",
            name="analysisfile",
            field=models.FileField(max_length=255, null=True, upload_to=""),
        ),
    ]
