# Generated by Django 5.0.3 on 2024-03-19 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0006_rename_is_scientist_user_is_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technition", "Technition"),
                    ("admin", "User Manager"),
                    ("supervisor", "Anaysis Supervisor"),
                    ("analysisManager", "Analysis Manager"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FinalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
