# Generated by Django 5.0.3 on 2024-05-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0007_remove_commentreports_fullreportfile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentreports",
            name="Picture",
        ),
    ]
