# Generated by Django 5.0.3 on 2024-03-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0008_finalcomment_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("comment", "Commnet"),
                            ("decision", "Decision"),
                            ("report", "report"),
                        ],
                        default="Not Selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FinalComment",
        ),
    ]
