# Generated by Django 5.0.6 on 2024-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0010_remove_dataset_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreports",
            name="problem",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("decision", "Decision"),
                    ("report", "Report"),
                    ("finaldecision", "Final Decision"),
                ],
                default="Not Selected",
                max_length=100,
                null=True,
            ),
        ),
    ]
