# Generated by Django 5.0.3 on 2024-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0012_rename_is_analysis_user_is_supervisor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreports",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="Pictures"),
        ),
    ]
