# Generated by Django 5.0.3 on 2024-03-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0003_user_city_analysisvaribales_commentreports_dataset"),
        ("kpi", "0013_commentreports_picture"),
    ]

    operations = []
